// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcCtogMo9OByxgnQ4GABEtWZlgetPkH78',
    appId: '1:811648134264:web:920180cd1e22833dbcd18d',
    messagingSenderId: '811648134264',
    projectId: 'wagewiser-cf14b',
    authDomain: 'wagewiser-cf14b.firebaseapp.com',
    storageBucket: 'wagewiser-cf14b.firebasestorage.app',
    measurementId: 'G-X9DW0XTS4Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZ87sE8py3NlY2lcs92ooneD0msJnyVts',
    appId: '1:811648134264:android:a5eb02e7cb58551cbcd18d',
    messagingSenderId: '811648134264',
    projectId: 'wagewiser-cf14b',
    storageBucket: 'wagewiser-cf14b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8R_o30fbvDv3j0ETJPF0qfDBUjlzC8eM',
    appId: '1:811648134264:ios:4a925c0f3812977dbcd18d',
    messagingSenderId: '811648134264',
    projectId: 'wagewiser-cf14b',
    storageBucket: 'wagewiser-cf14b.firebasestorage.app',
    iosBundleId: 'com.example.wagewiser',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8R_o30fbvDv3j0ETJPF0qfDBUjlzC8eM',
    appId: '1:811648134264:ios:4a925c0f3812977dbcd18d',
    messagingSenderId: '811648134264',
    projectId: 'wagewiser-cf14b',
    storageBucket: 'wagewiser-cf14b.firebasestorage.app',
    iosBundleId: 'com.example.wagewiser',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAcCtogMo9OByxgnQ4GABEtWZlgetPkH78',
    appId: '1:811648134264:web:98b9ffaecf094769bcd18d',
    messagingSenderId: '811648134264',
    projectId: 'wagewiser-cf14b',
    authDomain: 'wagewiser-cf14b.firebaseapp.com',
    storageBucket: 'wagewiser-cf14b.firebasestorage.app',
    measurementId: 'G-S0DD1RWRJD',
  );
}
